# Generated by Django 4.2.9 on 2024-02-05 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 15, 42, 34, 353892, tzinfo=datetime.timezone.utc), verbose_name='start date'),
        ),
    ]
