# Generated by Django 4.2.9 on 2024-02-21 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_appuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
    ]
