# Generated by Django 4.2.9 on 2024-04-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_communityactionstep_community_creator_and_more'),
        ('users', '0009_alter_appuser_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='community_collaborative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.communitycollaborative'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='system_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.systempartner'),
        ),
    ]
