# Generated by Django 4.2.9 on 2024-04-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_appuser_community_collaborative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='member_type',
            field=models.CharField(choices=[('CC', 'Community Collaborative Member'), ('SP', 'System Partner Member'), ('NT', 'NCFF Team Member')], default='CC', help_text='Type of member', max_length=2),
        ),
    ]
