# Generated by Django 4.2.9 on 2024-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_appuser_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='must_reset_password',
            field=models.BooleanField(default=True, help_text='Requires user to reset password on next login'),
        ),
    ]
