version: '3'

services:
  django_gunicorn:
    build: .
    restart: always
    env_file: .env
    environment:
      - DOMAIN=statewideplan.bringupnebraska.org
      - EMAIL=znelson@nebraskachildren.org
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swp.rule=Host(`statewideplan.bringupnebraska.org`)"
      - "traefik.http.routers.swp.entrypoints=websecure"
      - "traefik.http.routers.swp.tls.certresolver=letsencrypt"
      - "traefik.http.services.swp.loadbalancer.server.port=8000"
      - "traefik.http.routers.swp.tls=true"
    networks:
      - traefik_network
    volumes:
      - static_volume:/app/staticfiles

networks:
  traefik_network:
    external: true

volumes:
  static_volume: