version: '3'

services:
  django_gunicorn:
    build: .
    restart: always
    env_file: .env
    ports:
      - "8054:8000"
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "1335:80"
      - "13443:443"
    depends_on:
      - django_gunicorn
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
      - proxy-dhparams:/vol/proxy
      - static_volume:/vol/static
    env_file:
      - .env

  certbot:
    build: ./certbot
    command:
      - echo "Skipping..."
    env_file: .env
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - nginx


volumes:
  certbot-web:
  certbot-certs:
  static_volume:
  proxy-dhparams: