version: '3'

services:
  django_gunicorn:
    build: .
    restart: always
    env_file: .env
    environment:
      - VIRTUAL_HOST=statewideplan.bringupnebraska.org
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=statewideplan.bringupnebraska.org
      - LETSENCRYPT_EMAIL=znelson@nebraskachildren.org
    volumes:
      - static_volume:/app/staticfiles

volumes:
  static_volume: