version: '3'

services:
  django_gunicorn:
    build: .
    restart: always
    env_file: .env
    environment:
      - DOMAIN=statewideplan.ncffapps.dev
      - EMAIL=znelson@nebraskachildren.org
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swp-test.rule=Host(`statewideplan.ncffapps.dev`)"
      - "traefik.http.routers.swp-test.entrypoints=websecure"
      - "traefik.http.routers.swp-test.tls.certresolver=letsencrypt"
      - "traefik.http.services.swp-test.loadbalancer.server.port=8000"
      - "traefik.http.routers.swp-test.tls=true"
    networks:
      - traefik_network
    volumes:
      - static_volume:/app/staticfiles

networks:
  traefik_network:
    external: true

volumes:
  static_volume: