version: '3'

services:
  django_gunicorn:
    build: .
    restart: always
    env_file: .env
    environment:
      - VIRTUAL_HOST=statewideplan.bringupnebraska.org
      - LETSENCRYPT_HOST=statewideplan.bringupnebraska.org
      - LETSENCRYPT_EMAIL=znelson@nebraskachildren.org
    volumes:
      - static_volume:/app/staticfiles

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    labels:
      com.github.nginx-proxy.docker-gen: "true"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certbot-certs:/etc/nginx/certs:rw
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - proxy-dhparams:/etc/nginx/dhparam

  acme-companion:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certbot-certs:/etc/nginx/certs:rw
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy

volumes:
  certbot-certs:
  proxy-vhost:
  proxy-html:
  proxy-dhparams:
  static_volume: