# Generated by Django 4.2.9 on 2024-02-06 21:11

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='related_objective',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='related_goal', chained_model_field='related_goal', on_delete=django.db.models.deletion.CASCADE, to='core.objective'),
        ),
    ]
