# Generated by Django 4.2.9 on 2024-02-22 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activitystatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPartner',
            fields=[
                ('system_partner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_partner_name', models.CharField(max_length=75)),
                ('system_partner_short_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'System Partner to Align & Support',
                'verbose_name_plural': 'System Partners to Align & Support',
                'db_table': 'system_partners',
                'ordering': ('system_partner_name',),
            },
        ),
    ]
