# Generated by Django 4.2.9 on 2024-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systempartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='ncff_teams',
            field=models.ManyToManyField(blank=True, to='core.ncffteam'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='system_partners',
            field=models.ManyToManyField(blank=True, to='core.systempartner'),
        ),
    ]
