# Generated by Django 4.2.9 on 2024-02-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_strategy_ncff_teams_strategy_system_partners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategypriority',
            options={'ordering': ['community_collaborative', 'strategy'], 'verbose_name': 'Community Collab Priority', 'verbose_name_plural': 'Community Collab Priorities'},
        ),
        migrations.RenameField(
            model_name='strategypriority',
            old_name='community_collab',
            new_name='community_collaborative',
        ),
        migrations.AlterUniqueTogether(
            name='strategypriority',
            unique_together={('strategy', 'community_collaborative')},
        ),
        migrations.AddField(
            model_name='strategy',
            name='community_collaboratives',
            field=models.ManyToManyField(blank=True, through='core.StrategyPriority', to='core.communitycollaborative'),
        ),
        migrations.AddField(
            model_name='strategypriority',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
