# Generated by Django 4.2.9 on 2024-02-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_strategypriority_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactivity',
            name='activity_number',
            field=models.CharField(help_text='Automatically generated. No need to set manually.', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_number',
            field=models.CharField(help_text='Automatically generated. No need to set manually.', max_length=9),
        ),
        migrations.AlterField(
            model_name='strategyactivity',
            name='activity_number',
            field=models.CharField(help_text='Automatically generated. No need to set manually.', max_length=10),
        ),
    ]
