# Generated by Django 4.2.9 on 2024-02-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_communityactivity_activity_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyactivity',
            name='activity_details',
            field=models.TextField(max_length=1500),
        ),
    ]
