# Generated by Django 4.2.9 on 2024-03-22 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_communityactivity_activity_lead_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StrategyPriority',
            new_name='CollaborativeStrategyPriority',
        ),
        migrations.CreateModel(
            name='PartnerStrategyPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_priority', models.BooleanField(default=False)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.strategy')),
                ('system_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.systempartner')),
            ],
            options={
                'verbose_name': 'Partner Strategy Priority',
                'verbose_name_plural': 'Partner Strategy Priorities',
                'db_table': 'partner_strategy_priority',
                'ordering': ['system_partner', 'strategy'],
                'unique_together': {('strategy', 'system_partner')},
            },
        ),
        migrations.CreateModel(
            name='NcffTeamStrategyPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_priority', models.BooleanField(default=False)),
                ('ncff_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ncffteam')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.strategy')),
            ],
            options={
                'verbose_name': 'NCFF Team Priority',
                'verbose_name_plural': 'NCFF Team Priorities',
                'db_table': 'ncff_strategy_priority',
                'ordering': ['ncff_team', 'strategy'],
                'unique_together': {('strategy', 'ncff_team')},
            },
        ),
    ]
