# Generated by Django 4.2.9 on 2024-04-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_strategypriority_collaborativestrategypriority_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StrategyActivity',
            new_name='NCActionStep',
        ),
    ]
