# Generated by Django 4.2.9 on 2024-04-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_strategyactivity_ncactionstep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ncactionstep',
            options={'ordering': ['related_goal', 'related_objective', 'related_strategy', 'activity_number', 'completedby_year'], 'verbose_name': 'NC Action Step', 'verbose_name_plural': 'NC Action Steps'},
        ),
        migrations.AlterModelTable(
            name='ncactionstep',
            table='nc_actionstep',
        ),
    ]
