# Generated by Django 4.2.9 on 2024-04-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ncactionstep_options_alter_ncactionstep_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityActivity',
            new_name='CommunityActionStep',
        ),
        migrations.AlterModelOptions(
            name='communityactionstep',
            options={'ordering': ['related_collaborative', 'related_goal', 'related_objective', 'related_strategy', 'activity_status', 'completedby_year'], 'verbose_name': 'Community Action Steps', 'verbose_name_plural': 'Community Action Step'},
        ),
        migrations.AlterModelTable(
            name='communityactionstep',
            table='community_actionstep',
        ),
    ]
