# Generated by Django 4.2.9 on 2024-04-29 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_systempartnercommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityactionstep',
            name='community_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_community_action_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ncactionstep',
            name='nc_staff_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_nc_action_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systempartnercommitment',
            name='system_partner_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_system_partner_commitments', to=settings.AUTH_USER_MODEL),
        ),
    ]
