# Generated by Django 4.2.9 on 2024-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_communityactionstep_community_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycollaborative',
            name='community_collab_short_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
