# Generated by Django 4.2.9 on 2024-05-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_communitycollaborative_community_collab_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempartnercommitment',
            name='commitment_number',
            field=models.CharField(help_text='Automatically generated. No need to set manually.', max_length=12),
        ),
    ]
