# Generated by Django 4.2.9 on 2024-05-02 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_alter_systempartnercommitment_commitment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempartnercommitment',
            name='commitment_number',
            field=models.CharField(blank=True, help_text='Automatically generated. No need to set manually.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='systempartnercommitment',
            name='system_partner_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_system_partner_commitments', to=settings.AUTH_USER_MODEL),
        ),
    ]
