# Generated by Django 4.2.9 on 2024-05-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_systempartnercommitment_commitment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncactionstep',
            name='activity_number',
            field=models.CharField(blank=True, help_text='Automatically generated. No need to set manually.', max_length=10, null=True),
        ),
    ]
