# Generated by Django 4.2.9 on 2024-05-02 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_ncactionstep_activity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncactionstep',
            name='ncff_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_steps', to='core.ncffteam'),
        ),
    ]
