# Generated by Django 4.2.9 on 2024-05-02 03:16

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ncactionstep_ncff_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactionstep',
            name='related_objective',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='related_goal', chained_model_field='related_goal', on_delete=django.db.models.deletion.CASCADE, to='core.objective'),
        ),
        migrations.AlterField(
            model_name='communityactionstep',
            name='related_strategy',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='related_objective', chained_model_field='related_objective', on_delete=django.db.models.deletion.CASCADE, to='core.strategy'),
        ),
    ]
