# Generated by Django 4.2.9 on 2024-07-18 02:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_communityactionstep_related_objective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactionstep',
            name='activity_lead',
            field=models.CharField(blank=True, default='', help_text='Indicate who will lead the activity (person or organization).', max_length=100),
        ),
        migrations.AlterField(
            model_name='communityactionstep',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.goal'),
        ),
        migrations.AlterField(
            model_name='communityactionstep',
            name='related_objective',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='related_goal', chained_model_field='related_goal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.objective'),
        ),
        migrations.AlterField(
            model_name='communityactionstep',
            name='related_strategy',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='related_objective', chained_model_field='related_objective', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.strategy'),
        ),
        migrations.AlterField(
            model_name='ncactionstep',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.goal'),
        ),
        migrations.AlterField(
            model_name='ncactionstep',
            name='related_objective',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='related_goal', chained_model_field='related_goal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.objective'),
        ),
        migrations.AlterField(
            model_name='ncactionstep',
            name='related_strategy',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='related_objective', chained_model_field='related_objective', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.strategy'),
        ),
        migrations.AlterField(
            model_name='systempartnercommitment',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.goal'),
        ),
        migrations.AlterField(
            model_name='systempartnercommitment',
            name='related_objective',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='related_goal', chained_model_field='related_goal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.objective'),
        ),
        migrations.AlterField(
            model_name='systempartnercommitment',
            name='related_strategy',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='related_objective', chained_model_field='related_objective', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.strategy'),
        ),
    ]
