# Generated by Django 4.2.9 on 2024-07-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_communityactionstep_activity_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncactionstep',
            name='activity_number',
            field=models.CharField(blank=True, help_text='Automatically generated. No need to set manually.', max_length=15, null=True),
        ),
    ]
